name: Test conda env
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        env: [phobl.yaml]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
          activate-environment: test
      - run: mamba env create -f envs/${{ matrix.env }} --dry-run