name: Test conda env

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [phobl.yaml]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
      - run: conda env create -f ${{ matrix.env }} --dry-run